services:
  #dbコンテナ
  db:
    image: postgres:16
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql
  #api
  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: password
    ports:
      - "3000:3000"
    volumes:
      - .:/docker_rails_test
volumes:
  db-data: